import {useEffect,useRef,useState,type FormEvent,type ReactNode} from 'react';
import {ArrowDownToLine,ArrowRight,ArrowUpRight,Bell,CalendarDays,Check,CheckCheck,ChevronLeft,ChevronRight,Clock3,FileText,Home,Info,LayoutGrid,LogOut,Menu,Plus,Search,Settings2,ShieldCheck,Users,X,Mail,Send,BriefcaseBusiness,CheckCircle2,AlertCircle,SlidersHorizontal,Leaf,Save} from 'lucide-react';
import {ACTIVE,POSITIONS,addMonths,dateOnly,isWorking,monthDays,positionLabel,statusLabel,type Employee,type Leave,type LeaveInput,type Preview,type Quota} from '../shared/domain';
import {api,action,ApiError} from './api';
const fmt=(d:string,full=false)=>d?new Intl.DateTimeFormat('id-ID',{day:'numeric',month:full?'long':'short',...(full?{year:'numeric'}:{})}).format(new Date(d+'T00:00:00')):'—';
const monthLabel=(m:string)=>new Intl.DateTimeFormat('id-ID',{month:'long',year:'numeric'}).format(new Date(m+'-01T00:00:00'));
const initials=(name:string)=>name.split(' ').slice(0,2).map(n=>n[0]).join('');
const Badge=({status}:{status:Leave['status']})=><span className={'badge '+status.toLowerCase()}><span/>{statusLabel[status]}</span>;
const Empty=({title='Belum ada pengajuan',text=''}:{title?:string;text?:string})=><div className="empty"><FileText size={30}/><h3>{title}</h3>{text&&<p>{text}</p>}</div>;
const Field=({label,children,hint}:{label:string;children:ReactNode;hint?:string})=><label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>;
type Page='dashboard'|'requests'|'calendar'|'form'|'profile'|'admin'|'notifications';
export default function App(){
  const [config,setConfig]=useState<any>(null);const [user,setUser]=useState<Employee|null>(null);const [boot,setBoot]=useState(true);const [page,setPage]=useState<Page>('dashboard');
  const [month,setMonth]=useState(addMonths(dateOnly().slice(0,7)+'-01',1).slice(0,7));const [data,setData]=useState<any>(null);const [refresh,setRefresh]=useState(0);const [error,setError]=useState('');const [toast,setToast]=useState('');const [selected,setSelected]=useState<Leave|null>(null);const [draft,setDraft]=useState<Leave|null>(null);const [menu,setMenu]=useState(false);const [loading,setLoading]=useState(false);
  const sdm=user?.roles.includes('SDM');const admin=user?.roles.includes('ADMIN');
  useEffect(()=>{Promise.all([api('/config').then(setConfig),api<Employee>('/me').then(setUser).catch(()=>{})]).finally(()=>setBoot(false));},[]);
  useEffect(()=>{if(!user)return;let alive=true;setLoading(true);api('/dashboard?month='+month).then(d=>{if(alive){setData(d);setError('');}}).catch(e=>{if(e.status===401)setUser(null);else setError(e.message);}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[user,month,refresh]);
  useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(t);},[toast]);
  useEffect(()=>{if(!user)return;const id=new URLSearchParams(location.search).get('request');if(id)api<Leave>('/leave-requests/'+id).then(setSelected).catch(e=>setError(e.message));},[user]);
  const reload=()=>setRefresh(n=>n+1);const nav=(p:Page)=>{setPage(p);setMenu(false);setError('');};
  const newLeave=()=>{setDraft(null);nav('form');};
  if(boot)return <div className="boot"><div className="brand-word">BNI<span>•</span></div><p>Menyiapkan ruang kerja Anda…</p></div>;
  if(!user)return <Login config={config} onLogin={u=>{setData(null);setSelected(null);setUser(u);setPage('dashboard');}}/>;
  const pageTitles:Record<Page,string>={dashboard:'Ringkasan',requests:sdm?'Pengajuan cuti':'Pengajuan saya',calendar:'Kalender cuti',form:'Ajukan cuti',profile:'Profil saya',admin:'Administrasi',notifications:'Pusat notifikasi'};
  const navItems:[Page,typeof Home,string][]=[['dashboard',LayoutGrid,'Ringkasan'],['requests',FileText,sdm?'Pengajuan cuti':'Pengajuan saya'],['calendar',CalendarDays,'Kalender cuti']];
  const pending=data?.requests.filter((r:Leave)=>r.status==='PENDING_SDM').length??0;
  return <div className="app-shell">
    {menu&&<div className="menu-scrim" onClick={()=>setMenu(false)}/>}
    <aside className={'sidebar '+(menu?'open':'')}><div className="brand"><div className="brand-word">BNI<span>•</span></div><span className="brand-divider"/><div className="brand-product">Ruang Cuti</div></div>
      <div className="workspace"><div className="workspace-icon"><BriefcaseBusiness size={19}/></div><div><strong>{sdm?'Ruang kerja SDM':admin?'Administrator':'Ruang karyawan'}</strong><small>{data?.unitName??'Kantor Cabang'}</small></div></div>
      <nav>{navItems.map(([id,Icon,label])=><button key={id} className={page===id?'active':''} onClick={()=>nav(id)}><Icon size={19}/><span>{label}</span>{id==='requests'&&pending>0&&<b className="nav-count">{pending}</b>}</button>)}{!admin&&<button className={page==='form'?'active':''} onClick={newLeave}><Plus size={19}/><span>Ajukan cuti</span></button>}{admin&&<button className={page==='admin'?'active':''} onClick={()=>nav('admin')}><Settings2 size={19}/><span>Administrasi</span></button>}</nav>
      <div className="sidebar-bottom"><button className="user-card" onClick={()=>nav('profile')}><span className="avatar teal">{initials(user.name)}</span><span><strong>{user.name}</strong><small>{sdm?'Divisi Sumber Daya Manusia':positionLabel(user.position)}</small></span><ChevronRight size={16}/></button></div>
    </aside>
    <div className="main-shell"><header className="topbar"><button className="icon-button mobile-menu" aria-label="Buka menu" onClick={()=>setMenu(true)}><Menu/></button><div className="breadcrumb">Ruang Cuti <ChevronRight size={13}/><strong>{pageTitles[page]}</strong></div><div className="top-actions">{config?.demo&&<span className="demo-pill">Lingkungan demo</span>}<span className="today">{fmt(data?.today??config?.today??dateOnly(),true)}</span><button className="icon-button notification-button" aria-label="Notifikasi" onClick={()=>nav(admin?'admin':'notifications')}><Bell size={20}/>{pending>0&&<i/>}</button><button className="avatar small teal" aria-label="Profil saya" onClick={()=>nav('profile')}>{initials(user.name)}</button></div></header>
      <main><div className="page-heading"><div><h1>{pageTitles[page]}</h1></div>{['dashboard','requests','calendar'].includes(page)&&<div className="heading-actions"><label className="month-control"><CalendarDays size={17}/><input aria-label="Bulan monitoring" type="month" value={month} onChange={e=>{if(e.target.value)setMonth(e.target.value);}}/></label>{sdm?<a className="button secondary" href={'/api/reports.csv?month='+month}><ArrowDownToLine size={17}/>Unduh laporan</a>:!admin&&<button className="button primary" onClick={newLeave}><Plus size={18}/>Ajukan cuti</button>}</div>}</div>
      {error&&<div className="alert danger" role="alert">{error}<button onClick={reload}>Coba lagi</button></div>}
      {loading&&!data?<div className="skeleton-grid"><div/><div/><div/></div>:data&&<>
        {page==='dashboard'&&<Dashboard data={data} month={month} sdm={!!sdm} name={user.name} onSelect={setSelected} onRequests={()=>nav('requests')} onCalendar={()=>nav('calendar')} onNew={newLeave} admin={!!admin}/>}
        {page==='requests'&&<RequestList requests={data.requests} month={month} sdm={!!sdm} onSelect={setSelected} onDraft={(r:Leave)=>{setDraft(r);nav('form');}}/>}
        {page==='calendar'&&<CalendarView data={data} month={month} setMonth={setMonth} onSelect={(id:string)=>api<Leave>('/leave-requests/'+id).then(setSelected).catch(e=>setError(e.message))}/>}
        {page==='form'&&<LeaveForm key={draft?.id??'new'} user={user} today={data.today} draft={draft} calendar={data.calendarConfig} onDelete={()=>{reload();nav('requests');setToast('Draft dihapus.');}} onDone={r=>{if(r.effectiveStart)setMonth(r.effectiveStart.slice(0,7));reload();setSelected(r.status==='DRAFT'?null:r);nav('requests');setToast(r.status==='DRAFT'?'Draft tersimpan.':'Pengajuan berhasil dikirim ke SDM.');}}/>}
        {page==='profile'&&<section className="panel profile-panel"><span className="avatar large teal">{initials(user.name)}</span><h2>{user.name}</h2><p>{positionLabel(user.position)} • {data.unitName}</p><dl><dt>Email</dt><dd>{user.email}</dd><dt>Nomor HP</dt><dd>{user.phone}</dd><dt>Hak akses</dt><dd>{user.roles.join(', ')}</dd></dl><div className="alert info"><Info size={18}/>Perubahan kontak pada pengajuan tidak mengubah profil ini. Hubungi administrator untuk memperbarui profil.</div><button className="button secondary" onClick={async()=>{await action('/logout',{});setUser(null);setData(null);}}><LogOut size={17}/>Keluar dari akun</button></section>}
        {page==='notifications'&&<section className="panel"><div className="panel-heading"><h2>Aktivitas pengajuan</h2><span className="muted">Status terbaru</span></div>{data.requests.length?data.requests.filter((r:Leave)=>r.status!=='DRAFT').slice(0,15).map((r:Leave)=><button className="activity-row" key={r.id} onClick={()=>setSelected(r)}><span className="activity-icon"><Bell size={18}/></span><span><strong>{r.employeeName} • {r.number}</strong><small>{r.events.at(-1)?.text} · {fmt(r.effectiveStart)}</small></span><Badge status={r.status}/></button>):<Empty title="Belum ada aktivitas"/>}</section>}
        {page==='admin'&&admin&&<Admin onChange={reload} onToast={setToast} today={data.today}/>}
      </>}

      </main>
    </div>
    {toast&&<div className="toast" role="status"><CheckCircle2 size={19}/>{toast}</div>}
    {selected&&<Detail leave={selected} user={user} today={data?.today??dateOnly()} onClose={()=>setSelected(null)} onCopy={()=>{setDraft({...selected,id:'',status:'DRAFT',version:0});setSelected(null);nav('form');}} onUpdate={r=>{setSelected(r);reload();setToast('Pengajuan berhasil diperbarui.');}}/>}
  </div>;
}
function Login({config,onLogin}:{config:any;onLogin:(u:Employee)=>void}){
  const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  async function login(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{onLogin(await action('/login',{email,password}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <div className="login"><div className="login-main"><div className="login-box"><div className="brand-word">BNI<span>•</span></div><h2>Ruang Cuti</h2><form onSubmit={login}><Field label="Email karyawan"><input type="email" autoComplete="username" placeholder="nama@perusahaan.co.id" value={email} onChange={e=>setEmail(e.target.value)} required/></Field><Field label="Kata sandi"><input type="password" autoComplete="current-password" placeholder="Masukkan kata sandi" value={password} onChange={e=>setPassword(e.target.value)} required/></Field>{error&&<div className="alert danger" role="alert">{error}</div>}<button className="button primary full" disabled={busy}>{busy?'Memeriksa akun…':'Masuk'}<ArrowRight size={18}/></button></form>{config?.demo&&<div className="demo-accounts"><span>AKUN DEMO</span><div>{[['SDM','sdm'],['Karyawan','karyawan'],['Admin','admin']].map(([label,account])=><button key={account} onClick={()=>{setEmail(account+'@demo.bni.local');setPassword('BniCuti!2026');setError('');}}>{label}<ArrowUpRight size={13}/></button>)}</div><small>Data contoh untuk uji coba.</small></div>}</div></div></div>;
}
function Dashboard({data,month,sdm,onSelect,onRequests,onCalendar}:any){
  const current:Leave[]=data.requests.filter((r:Leave)=>r.effectiveStart.startsWith(month)&&r.status!=='DRAFT');const waiting=current.filter(r=>r.status==='PENDING_SDM');const approved=current.filter(r=>r.status==='APPROVED');const quotas:Quota[]=data.quotas;const used=quotas.reduce((a,q)=>a+q.used,0);const total=quotas.reduce((a,q)=>a+q.limit,0);
  return <>
    <div className="stats-grid">{[
      {label:'Total pengajuan',value:current.length,unit:'pengajuan'},
      {label:'Menunggu SDM',value:waiting.length,unit:'pengajuan'},
      {label:'Disetujui',value:approved.length,unit:'pengajuan'},
      {label:'Kuota terpakai',value:used,unit:`/ ${total} orang`},
    ].map(s=><article className="stat-card" key={s.label}><div className="stat-head"><span>{s.label}</span></div><div className="stat-value">{s.value}<span>{s.unit}</span></div></article>)}</div>
    <div className="dashboard-grid"><section className="panel requests-panel"><div className="panel-heading"><div><h2>{sdm?'Pengajuan terbaru':'Pengajuan Anda'} <span className="count-bubble">{current.length}</span></h2></div><button className="text-button" onClick={onRequests}>Lihat semua<ArrowRight size={15}/></button></div><RequestTable requests={current.slice(0,5)} onSelect={onSelect} compact/></section>
      <section className="panel quota-panel"><div className="panel-heading"><div><h2>Kuota per posisi</h2><p>{monthLabel(month)} · dalam orang</p></div><Users size={19} className="muted"/></div><div className="quota-list">{quotas.slice(0,sdm?6:14).map(q=><div className="quota-row" key={q.position}><div><strong>{q.label}</strong><span><b>{q.used}</b> / {q.limit} <small>orang</small></span></div><div className="progress-track"><span style={{width:(q.limit?100*q.approved/q.limit:0)+'%'}}/><i style={{width:(q.limit?100*q.pending/q.limit:0)+'%'}}/></div></div>)}</div><div className="legend"><span><i className="teal-dot"/>Disetujui</span><span><i className="orange-dot"/>Menunggu</span><span><i className="gray-dot"/>Tersedia</span></div><button className="quota-link" onClick={onCalendar}>Lihat kalender<ArrowRight size={16}/></button></section>
    </div>

  </>;
}
function RequestTable({requests,onSelect,compact=false,onDraft}:{requests:Leave[];onSelect:(r:Leave)=>void;compact?:boolean;onDraft?:(r:Leave)=>void}){return requests.length?<div className="table-scroll"><table><thead><tr><th>Karyawan</th><th>Jadwal cuti</th>{!compact&&<th>Jenis</th>}<th>Status</th><th aria-label="Aksi"/></tr></thead><tbody>{requests.map((r,i)=><tr key={r.id}><td><div className="person"><span className="avatar neutral">{initials(r.employeeName)}</span><div><strong>{r.employeeName}</strong><small>{positionLabel(r.position)}</small></div></div></td><td><span className="date-range">{fmt(r.effectiveStart||r.start)}{r.effectiveEnd!==r.effectiveStart?' – '+fmt(r.effectiveEnd||r.end):''}</span><small>{r.duration} hari kerja</small></td>{!compact&&<td><span className={'category '+r.category.toLowerCase()}>{r.category==='REGULAR'?'Reguler':'Darurat'}</span><small>{r.number}</small></td>}<td><Badge status={r.status}/></td><td><button className="icon-button table-arrow" aria-label={'Lihat '+r.employeeName+' '+r.number} onClick={()=>r.status==='DRAFT'&&onDraft?onDraft(r):onSelect(r)}><ArrowUpRight size={17}/></button></td></tr>)}</tbody></table></div>:<Empty/>;}
function RequestList({requests,month,sdm,onSelect,onDraft}:any){const [query,setQuery]=useState('');const [status,setStatus]=useState('ALL');const filtered=requests.filter((r:Leave)=>(r.effectiveStart.startsWith(month)||r.status==='DRAFT')&&(status==='ALL'||r.status===status)&&`${r.employeeName} ${r.number} ${positionLabel(r.position)}`.toLowerCase().includes(query.toLowerCase()));return <section className="panel"><div className="list-toolbar"><div className="tabs">{[['ALL','Semua'],['PENDING_SDM','Menunggu'],['APPROVED','Disetujui'],['REJECTED','Ditolak'],...(!sdm?[['DRAFT','Draft'],['WITHDRAWN','Ditarik']]:[])].map(([id,label])=><button key={id} className={status===id?'selected':''} onClick={()=>setStatus(id)}>{label}</button>)}</div><label className="search"><Search size={17}/><input aria-label="Cari pengajuan" placeholder="Cari nama atau nomor…" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><RequestTable requests={filtered} onSelect={onSelect} onDraft={onDraft}/><div className="table-footer">Menampilkan {filtered.length} pengajuan · {monthLabel(month)}</div></section>;}
function CalendarView({data,month,setMonth,onSelect}:any){const [position,setPosition]=useState('ALL');const days=monthDays(month);const offset=(new Date(month+'-01T00:00:00').getDay()+6)%7;const entries=data.calendar.filter((r:any)=>position==='ALL'||r.position===position);return <><section className="panel calendar-panel"><div className="panel-heading"><div className="calendar-heading"><button className="icon-button" aria-label="Bulan sebelumnya" onClick={()=>setMonth(addMonths(month+'-01',-1).slice(0,7))}><ChevronLeft size={18}/></button><h2>{monthLabel(month)}</h2><button className="icon-button" aria-label="Bulan berikutnya" onClick={()=>setMonth(addMonths(month+'-01',1).slice(0,7))}><ChevronRight size={18}/></button></div><select aria-label="Filter posisi kalender" value={position} onChange={e=>setPosition(e.target.value)}><option value="ALL">Semua posisi</option>{data.quotas.map((q:Quota)=><option key={q.position} value={q.position}>{q.label}</option>)}</select></div><div className="calendar-scroll"><div className="calendar-grid">{['Sen','Sel','Rab','Kam','Jum','Sab','Min'].map(d=><div className="weekday" key={d}>{d}</div>)}{Array.from({length:offset},(_,i)=><div className="day outside" key={'o'+i}/>)}{days.map(d=>{const blocked=data.blocked.includes(d);const off=!isWorking(d,data.calendarConfig);return <div key={d} className={'day '+(blocked?'blocked ':'')+(off?'off ':'')+(d===data.today?'current':'')}><div className="day-number">{Number(d.slice(-2))}{blocked&&<small>H-3</small>}</div>{data.calendarConfig.exceptions[d]&&<small className="holiday-label">{data.calendarConfig.exceptions[d].label}</small>}{entries.filter((r:any)=>r.days.includes(d)).map((r:any,i:number)=><button disabled={!r.id} key={r.id+'-'+i} onClick={()=>onSelect(r.id)} className={'calendar-event '+(r.status==='APPROVED'?'approved':'pending')}><span>{r.name}</span><small>{positionLabel(r.position)} · {r.status==='APPROVED'?'Disetujui':'Menunggu'}</small></button>)}</div>;})}</div></div><div className="legend calendar-legend"><span><i className="teal-dot"/>Disetujui</span><span><i className="orange-dot"/>Menunggu SDM</span><span><i className="blocked-dot"/>3 hari kerja terakhir</span><span>Kalender kerja unit: Senin–Jumat + pengecualian admin</span></div></section><section className="panel all-quotas"><div className="panel-heading"><h2>Kapasitas posisi bulan ini</h2><span className="muted">Terpakai / kuota orang</span></div><div className="quota-cards">{data.quotas.map((q:Quota)=><div key={q.position}><strong>{q.label}</strong><span>{q.used}<small> / {q.limit}</small></span><p>{q.available} orang tersedia</p></div>)}</div></section></>;}

function LeaveForm({user,today,draft,calendar,onDone,onDelete}:{user:Employee;today:string;draft:Leave|null;calendar:any;onDone:(r:Leave)=>void;onDelete:()=>void}){
  const [input,setInput]=useState<LeaveInput>(draft?{category:draft.category,subtype:draft.subtype,reason:draft.reason,start:draft.start,end:draft.end,email:draft.email,phone:draft.phone}:{category:'REGULAR',subtype:'',reason:'',start:'',end:'',email:user.email,phone:user.phone});
  const [emergencyType,setEmergencyType]=useState(draft&&['Cuti Duka','Cuti Sakit'].includes(draft.subtype)?draft.subtype:'Lainnya');const [p,setP]=useState<Preview|null>(null);const [error,setError]=useState('');const [checking,setChecking]=useState(false);const [busy,setBusy]=useState(false);const [accepted,setAccepted]=useState(false);const [review,setReview]=useState(false);const [deleting,setDeleting]=useState(false);const submitKey=useRef(crypto.randomUUID());
  const update=(key:keyof LeaveInput,value:string)=>{setInput(v=>({...v,[key]:value}));setP(null);setReview(false);setAccepted(false);submitKey.current=crypto.randomUUID();};
  useEffect(()=>{let active=true;setP(null);setError('');if(!input.start||!input.end||input.reason.trim().length<10||input.subtype.trim().length<2||!input.email||input.phone.length<8){setChecking(false);return;}
    setChecking(true);const timer=setTimeout(()=>{action('/leave-requests/preview',input).then(result=>{if(active)setP(result);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setChecking(false);});},350);return()=>{active=false;clearTimeout(timer);};
  },[input]);
  const minimum=input.category==='REGULAR'?addMonths(today,1):today;
  async function send(){setBusy(true);setError('');try{onDone(await action('/leave-requests',{...input,fingerprint:p?.fingerprint,acceptAdjustment:accepted,draftId:draft?.id,draftVersion:draft?.version},submitKey.current));}catch(e){setError((e as Error).message);if(e instanceof ApiError&&e.details){setP(e.details);setReview(false);setAccepted(false);submitKey.current=crypto.randomUUID();}}finally{setBusy(false);}}
  async function save(){setBusy(true);try{onDone(await action('/drafts',{...input,id:draft?.id||undefined,version:draft?.id?draft.version:undefined}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <div className="form-layout"><section className="panel form-panel"><div className="section-number"><b>01</b><div><h2>Detail pengajuan</h2><p>{user.name} · {positionLabel(user.position)}</p></div></div><div className="category-options"><button className={input.category==='REGULAR'?'chosen':''} onClick={()=>{update('category','REGULAR');update('subtype','');}}><CalendarDays size={23}/><strong>Cuti reguler</strong><small>Rencanakan satu bulan sebelumnya</small>{input.category==='REGULAR'&&<CheckCircle2 size={17}/>}</button><button className={input.category==='EMERGENCY'?'chosen':''} onClick={()=>{update('category','EMERGENCY');update('subtype','Cuti Duka');setEmergencyType('Cuti Duka');}}><Clock3 size={23}/><strong>Cuti darurat</strong><small>Tanpa masa tunggu satu bulan</small>{input.category==='EMERGENCY'&&<CheckCircle2 size={17}/>}</button></div>
      {input.category==='EMERGENCY'?<><Field label="Jenis cuti darurat"><select value={emergencyType} onChange={e=>{setEmergencyType(e.target.value);update('subtype',e.target.value==='Lainnya'?'':e.target.value);}}><option>Cuti Duka</option><option>Cuti Sakit</option><option>Lainnya</option></select></Field>{emergencyType==='Lainnya'&&<Field label="Nama jenis cuti"><input value={input.subtype} onChange={e=>update('subtype',e.target.value)} maxLength={120}/></Field>}</>:<Field label="Jenis cuti"><input placeholder="Contoh: keperluan keluarga" value={input.subtype} onChange={e=>update('subtype',e.target.value)} maxLength={120}/></Field>}
      <Field label="Alasan pengajuan" hint="Minimal 10 karakter. Alasan hanya dapat dilihat oleh Anda dan SDM berwenang."><textarea rows={3} value={input.reason} onChange={e=>update('reason',e.target.value)} placeholder="Ceritakan keperluan cuti Anda…" maxLength={2000}/></Field>
      <div className="section-number separated"><b>02</b><div><h2>Jadwal cuti</h2></div></div><div className="alert info"><Info size={18}/><span>{input.category==='REGULAR'?`Batas masa tunggu: ${fmt(minimum,true)}. `:'Cuti darurat dapat dimulai hari ini. '}Hindari 3 hari kerja terakhir bulan; maksimal 5 hari kerja.</span></div><div className="field-grid"><Field label="Tanggal mulai"><input type="date" min={minimum} value={input.start} onChange={e=>update('start',e.target.value)}/></Field><Field label="Tanggal akhir"><input type="date" min={input.start||minimum} value={input.end} onChange={e=>update('end',e.target.value)}/></Field></div>
      {input.start&&!isWorking(input.start,calendar)&&<div className="alert danger">Tanggal mulai bukan hari kerja. Pilih hari kerja lain.</div>}
      <div className="section-number separated"><b>03</b><div><h2>Informasi kontak</h2></div></div><div className="field-grid"><Field label="Nomor HP"><input type="tel" value={input.phone} onChange={e=>update('phone',e.target.value)}/></Field><Field label="Email pemberitahuan"><input type="email" value={input.email} onChange={e=>update('email',e.target.value)}/></Field></div>
      {error&&<div className="alert danger" role="alert">{error}</div>}<div className="form-actions"><button className="button secondary" disabled={busy} onClick={save}><Save size={17}/>Simpan draft</button><button className="button primary" disabled={busy||checking||!p||!!p.errors.length} onClick={()=>setReview(true)}>Tinjau pengajuan<ArrowRight size={17}/></button></div>{draft?.id&&<button className="text-button" disabled={busy} onClick={()=>setDeleting(true)}>Hapus draft ini</button>}
    </section><aside className="form-summary panel"><h2>Ringkasan cuti</h2>{checking?<p role="status">Menghitung tanggal dan kuota…</p>:p?<><div className="duration"><strong>{p.duration}</strong><span>hari kerja</span></div><dl><dt>Tanggal diminta</dt><dd>{fmt(input.start)} – {fmt(input.end)}</dd><dt>Tanggal efektif</dt><dd>{fmt(p.effectiveStart)} – {fmt(p.effectiveEnd)}</dd><dt>Kuota tersedia</dt><dd>{p.quota.available} dari {p.quota.limit} orang</dd><dt>Tambahan pemakaian</dt><dd>{p.quota.alreadyCounted?'0 (Anda sudah terhitung)':'1 orang'}</dd><dt>Status awal</dt><dd>Menunggu SDM</dd></dl>{p.adjusted&&<div className="alert warning"><Info size={17}/><span>Tanggal akhir disesuaikan menjadi {fmt(p.effectiveEnd,true)} mengikuti hari kerja dan batas H-3.</span></div>}{p.errors.map(e=><div className="alert danger" key={e.code} role="alert">{e.message}</div>)}{p.scheduledAt&&<div className="email-note"><Mail size={18}/><span>Pengingat SDM: {new Date(p.scheduledAt).toLocaleString('id-ID',{timeZone:'Asia/Jakarta'})} WIB</span></div>}</>:<div className="summary-placeholder"><CalendarDays size={38}/><p>Lengkapi form untuk melihat ringkasan.</p></div>}</aside>
    {review&&p&&<Modal title="Tinjau pengajuan cuti" onClose={()=>setReview(false)}><Badge status="DRAFT"/><h3>{input.subtype}</h3><p className="reason-text">{input.reason}</p><dl><dt>Kategori</dt><dd>{input.category==='REGULAR'?'Reguler':'Darurat'}</dd><dt>Tanggal diminta</dt><dd>{fmt(input.start,true)} – {fmt(input.end,true)}</dd><dt>Tanggal efektif</dt><dd>{fmt(p.effectiveStart,true)} – {fmt(p.effectiveEnd,true)}</dd><dt>Durasi</dt><dd>{p.duration} hari kerja · {p.quota.alreadyCounted?'slot sudah terhitung':'1 slot orang'}</dd><dt>Kontak</dt><dd>{input.phone}<br/>{input.email}</dd></dl>{p.adjusted&&<label className="checkbox"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/>Saya memahami tanggal dan durasi yang disesuaikan.</label>}{error&&<div className="alert danger">{error}</div>}<div className="modal-actions"><button className="button secondary" onClick={()=>setReview(false)}>Kembali</button><button className="button primary" disabled={busy||(p.adjusted&&!accepted)} onClick={send}><Send size={17}/>{busy?'Mengirim…':'Kirim pengajuan'}</button></div></Modal>}
    {deleting&&<Modal title="Hapus draft?" onClose={()=>setDeleting(false)}><p className="reason-text">Draft ini akan dihapus. Kuota tidak berubah karena draft belum memakai slot.</p><div className="modal-actions"><button className="button secondary" onClick={()=>setDeleting(false)}>Kembali</button><button className="button danger-button" disabled={busy} onClick={async()=>{setBusy(true);try{await api('/drafts/'+draft!.id,{method:'DELETE',key:crypto.randomUUID()});onDelete();}catch(e){setError((e as Error).message);setDeleting(false);}finally{setBusy(false);}}}>Hapus draft</button></div></Modal>}
  </div>;
}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const old=document.activeElement as HTMLElement;const before=document.body.style.overflow;document.body.style.overflow='hidden';ref.current?.querySelector<HTMLButtonElement>('button')?.focus();const handler=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const list=Array.from(ref.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select,textarea,a[href]')??[]);if(e.shiftKey&&document.activeElement===list[0]){e.preventDefault();list.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===list.at(-1)){e.preventDefault();list[0]?.focus();}}};document.addEventListener('keydown',handler);return()=>{document.body.style.overflow=before;document.removeEventListener('keydown',handler);old?.focus();};},[]);return <div className="modal-backdrop"><div className="modal" ref={ref} role="dialog" aria-modal="true" aria-label={title}><div className="modal-header"><h2>{title}</h2><button className="icon-button" aria-label="Tutup dialog" onClick={onClose}><X size={21}/></button></div><div className="modal-body">{children}</div></div></div>;}
function Detail({leave:r,user,today,onClose,onUpdate,onCopy}:{leave:Leave;user:Employee;today:string;onClose:()=>void;onUpdate:(r:Leave)=>void;onCopy:()=>void}){const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [reason,setReason]=useState('');const [channel,setChannel]=useState('Telepon');const [confirmAction,setConfirmAction]=useState('');const canReview=user.roles.includes('SDM')&&r.employeeId!==user.id&&r.status==='PENDING_SDM';
  async function update(actionName:string,body:any){setBusy(true);setError('');try{onUpdate(await action('/leave-requests/'+r.id+'/'+actionName,{...body,version:r.version}));setConfirmAction('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <Modal title={'Detail '+r.number} onClose={onClose}><div className="detail-title"><div className="person"><span className="avatar teal">{initials(r.employeeName)}</span><div><h3>{r.employeeName}</h3><p>{positionLabel(r.position)} · {r.category==='REGULAR'?'Reguler':'Darurat'}</p></div></div><Badge status={r.status}/></div><div className="detail-dates"><div><small>Tanggal efektif</small><strong>{fmt(r.effectiveStart,true)} – {fmt(r.effectiveEnd,true)}</strong></div><b>{r.duration}<small>hari kerja</small></b></div><dl><dt>Tanggal diminta</dt><dd>{fmt(r.start,true)} – {fmt(r.end,true)}</dd><dt>Jenis cuti</dt><dd>{r.subtype}</dd><dt>Email</dt><dd>{r.email}</dd><dt>Nomor HP</dt><dd>{r.phone}</dd><dt>Versi kalender</dt><dd>{r.calendarVersion} · Kuota {r.limit} orang</dd></dl><h4>Alasan pengajuan</h4><p className="reason-text">{r.reason}</p>{r.decisionReason&&<div className="alert info"><span><strong>Catatan keputusan</strong><br/>{r.decisionReason}</span></div>}
    <h4>Aktivitas pengajuan</h4><div className="timeline">{r.events.map((e,i)=><div key={i}><i/><strong>{e.text}</strong><small>{e.actor} · {new Date(e.at).toLocaleString('id-ID',{timeZone:'Asia/Jakarta'})} WIB</small></div>)}</div>
    {r.status==='PENDING_SDM'&&r.effectiveStart<today&&<div className="alert danger">Tanggal mulai sudah terlewati. Persetujuan tidak lagi tersedia.</div>}
    {canReview&&r.category==='REGULAR'&&<div className="confirmation-box"><h4>Konfirmasi karyawan</h4><p>{r.confirmation==='CONFIRMED'?'Karyawan telah mengonfirmasi jadi mengambil cuti.':r.confirmation==='DECLINED'?'Karyawan tidak jadi cuti. Tolak pengajuan untuk menyelesaikan proses.':'Hubungi karyawan lalu catat hasil konfirmasinya.'}</p><Field label="Kanal konfirmasi"><input value={channel} onChange={e=>setChannel(e.target.value)} maxLength={120}/></Field><div className="inline-actions"><button disabled={busy} className="button secondary" onClick={()=>update('confirmation',{result:'CONFIRMED',channel})}><Check size={16}/>Jadi mengambil cuti</button><button disabled={busy} className="text-button" onClick={()=>update('confirmation',{result:'DECLINED',channel})}>Tidak jadi</button></div></div>}
    {error&&<div className="alert danger" role="alert">{error}</div>}{r.employeeId===user.id&&['REJECTED','WITHDRAWN'].includes(r.status)&&<button className="button secondary" onClick={onCopy}><Plus size={17}/>Salin ke pengajuan baru</button>}
    {confirmAction?<div className="decision-box"><h4>{confirmAction==='WITHDRAWN'?'Tarik pengajuan ini?':confirmAction==='APPROVED'?'Setujui pengajuan ini?':'Tolak pengajuan ini?'}</h4>{confirmAction==='REJECTED'?<Field label="Alasan penolakan"><textarea value={reason} onChange={e=>setReason(e.target.value)} minLength={5} maxLength={2000} placeholder="Jelaskan alasan penolakan…"/></Field>:<p>{confirmAction==='WITHDRAWN'?'Slot orang dilepas jika Anda tidak memiliki pengajuan aktif lain pada bulan ini.':'Keputusan akan dicatat dan pemberitahuan diantrekan ke email karyawan.'}</p>}<div className="modal-actions"><button className="button secondary" onClick={()=>setConfirmAction('')}>Kembali</button><button className={'button '+(confirmAction==='APPROVED'?'primary':'danger-button')} disabled={busy||(confirmAction==='REJECTED'&&reason.trim().length<5)} onClick={()=>update(confirmAction==='WITHDRAWN'?'withdraw':'decision',{outcome:confirmAction,reason})}>{busy?'Menyimpan…':'Konfirmasi keputusan'}</button></div></div>:<div className="modal-actions">{r.status==='PENDING_SDM'&&r.employeeId===user.id&&<button className="button secondary" onClick={()=>setConfirmAction('WITHDRAWN')}>Tarik pengajuan</button>}{canReview&&<><button className="button secondary" onClick={()=>setConfirmAction('REJECTED')}>Tolak pengajuan</button><button className="button primary" disabled={busy||r.effectiveStart<today||(r.category==='REGULAR'&&r.confirmation!=='CONFIRMED')} onClick={()=>setConfirmAction('APPROVED')}><Check size={17}/>Setujui pengajuan</button></>}</div>}
  </Modal>;
}
function Admin({onChange,onToast,today}:{onChange:()=>void;onToast:(s:string)=>void;today:string}){const [data,setData]=useState<any>(null);const [tab,setTab]=useState('employees');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [editing,setEditing]=useState<any>(null);const [date,setDate]=useState('');const [label,setLabel]=useState('');const [working,setWorking]=useState(false);const [qm,setQm]=useState(addMonths(today.slice(0,7)+'-01',1).slice(0,7));const [pos,setPos]=useState('CS_BINA');const [limit,setLimit]=useState(2);
  const load=()=>api('/admin').then(setData).catch(e=>setError(e.message));useEffect(()=>{load();},[]);
  async function save(path:string,body:any){setBusy(true);setError('');try{await action('/admin/'+path,body);await load();onChange();onToast('Perubahan berhasil disimpan.');setEditing(null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  if(!data)return <div className="panel empty">{error||'Memuat administrasi…'}</div>;
  return <section className="panel"><div className="list-toolbar"><div className="tabs">{[['employees','Karyawan'],['quota','Posisi & kuota'],['calendar','Kalender kerja'],['jobs','Notifikasi email'],['audit','Audit']].map(([id,name])=><button key={id} className={tab===id?'selected':''} onClick={()=>{setTab(id);setError('');}}>{name}</button>)}</div></div>{error&&<div className="alert danger margin" role="alert">{error}</div>}
    {tab==='employees'&&<><div className="panel-heading"><div><h2>Direktori karyawan</h2><p>Akses dan penempatan karyawan pada unit ini.</p></div><button className="button primary" onClick={()=>setEditing({name:'',email:'',phone:'',position:'CS_BINA',roles:['EMPLOYEE'],active:true,password:''})}><Plus size={17}/>Tambah karyawan</button></div><div className="table-scroll"><table><thead><tr><th>Nama</th><th>Posisi</th><th>Akses</th><th>Status</th><th/></tr></thead><tbody>{data.employees.map((e:Employee)=><tr key={e.id}><td><strong>{e.name}</strong><small>{e.email}</small></td><td>{positionLabel(e.position)}</td><td>{e.roles.join(', ')}</td><td>{e.active?'Aktif':'Nonaktif'}</td><td><button className="text-button" onClick={()=>setEditing({...e,password:''})}>Edit</button></td></tr>)}</tbody></table></div></>}
    {tab==='quota'&&<div className="admin-content"><h2>Kuota orang per posisi</h2><p className="muted">Berlaku per bulan dan sekaligus menjadi batas orang cuti bersamaan. Periode yang sudah memiliki alokasi dibekukan.</p><div className="field-grid three"><Field label="Bulan berlaku"><input type="month" value={qm} onChange={e=>setQm(e.target.value)}/></Field><Field label="Posisi"><select value={pos} onChange={e=>{setPos(e.target.value);setLimit(POSITIONS.find(p=>p[0]===e.target.value)![2]);}}>{POSITIONS.map(([p,l])=><option key={p} value={p}>{l}</option>)}</select></Field><Field label="Kuota orang"><input type="number" min={0} max={1000} value={limit} onChange={e=>setLimit(+e.target.value)}/></Field></div><button className="button primary" disabled={busy} onClick={()=>save('quota',{month:qm,position:pos,limit})}>Simpan kuota periode</button><div className="quota-cards admin-quotas">{POSITIONS.map(([p,l,q])=><div key={p}><strong>{l}</strong><span>{data.policy.quotas[Object.keys(data.policy.quotas).filter(m=>m<=qm).sort().at(-1)??'']?.[p]??q}<small> orang</small></span></div>)}</div></div>}
    {tab==='calendar'&&<div className="admin-content"><h2>Kalender kerja unit</h2><p className="muted">Pola kerja Senin–Jumat. Tambahkan libur atau hari kerja khusus. Perubahan H-3 yang menyentuh cuti aktif akan ditolak.</p><div className="field-grid three"><Field label="Tanggal pengecualian"><input type="date" min={today} value={date} onChange={e=>setDate(e.target.value)}/></Field><Field label="Keterangan"><input value={label} onChange={e=>setLabel(e.target.value)} placeholder="Contoh: libur unit"/></Field><Field label="Jenis hari"><select value={String(working)} onChange={e=>setWorking(e.target.value==='true')}><option value="false">Hari libur</option><option value="true">Hari kerja khusus</option></select></Field></div><button className="button primary" disabled={busy||!date||label.length<2} onClick={()=>save('calendar',{date,label,working})}>Simpan kalender</button><div className="exception-list">{Object.entries(data.policy.calendar.exceptions).map(([d,v]:any)=><div key={d}><span><strong>{fmt(d,true)}</strong> · {v.label} · {v.working?'Kerja':'Libur'}</span><button className="text-button" disabled={busy} onClick={()=>save('calendar',{date:d,label:v.label,working:v.working,remove:true})}>Hapus pengecualian</button></div>)}</div></div>}
    {tab==='jobs'&&<div className="admin-content"><h2>Pengiriman notifikasi</h2><div className="alert info"><Mail size={18}/><span>CAPTURED berarti email ditampung lokal untuk simulasi, bukan terkirim ke inbox. Penerima SDM mengikuti akun SDM aktif pada unit ini.</span></div>{data.jobs.length?<div className="table-scroll"><table><thead><tr><th>Jenis</th><th>Jadwal</th><th>Status</th><th>Upaya gagal</th><th/></tr></thead><tbody>{data.jobs.map((j:any)=><tr key={j.id}><td>{j.kind}</td><td>{new Date(j.due_at).toLocaleString('id-ID',{timeZone:'Asia/Jakarta'})}</td><td>{j.state}<small>{j.last_error}</small></td><td>{j.attempts}</td><td>{j.state==='FAILED'&&<button className="text-button" disabled={busy} onClick={()=>save('jobs/'+j.id+'/retry',{})}>Coba ulang</button>}</td></tr>)}</tbody></table></div>:<Empty title="Belum ada email dalam antrean" text="Pengajuan baru dan keputusan SDM akan membuat notifikasi."/>}</div>}
    {tab==='audit'&&<div className="admin-content"><h2>Jejak aktivitas</h2>{data.audit.length?<div className="table-scroll"><table><thead><tr><th>Waktu</th><th>Pengguna</th><th>Aksi</th><th>Objek</th></tr></thead><tbody>{data.audit.map((a:any)=><tr key={a.id}><td>{new Date(a.at).toLocaleString('id-ID')}</td><td>{data.employees.find((e:Employee)=>e.id===a.actor_id)?.name??a.actor_id}</td><td>{a.action}</td><td className="mono">{a.object_id}</td></tr>)}</tbody></table></div>:<Empty title="Belum ada aktivitas tercatat"/>}</div>}
    {editing&&<Modal title={editing.id?'Edit karyawan':'Tambah karyawan'} onClose={()=>setEditing(null)}><form onSubmit={e=>{e.preventDefault();const {unit,...body}=editing;if(!body.password)delete body.password;save('employee',body);}}><Field label="Nama lengkap"><input required value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></Field><div className="field-grid"><Field label="Email"><input type="email" required value={editing.email} onChange={e=>setEditing({...editing,email:e.target.value})}/></Field><Field label="Nomor HP"><input required value={editing.phone} onChange={e=>setEditing({...editing,phone:e.target.value})}/></Field></div><Field label="Posisi"><select value={editing.position} onChange={e=>setEditing({...editing,position:e.target.value})}>{POSITIONS.map(([p,l])=><option key={p} value={p}>{l}</option>)}</select></Field><Field label={editing.id?'Kata sandi baru (kosongkan jika tetap)':'Kata sandi awal'}><input type="password" minLength={12} required={!editing.id} autoComplete="new-password" value={editing.password} onChange={e=>setEditing({...editing,password:e.target.value})}/></Field><div className="inline-actions">{['EMPLOYEE','SDM','ADMIN'].map(role=><label className="checkbox" key={role}><input type="checkbox" checked={editing.roles.includes(role)} onChange={e=>setEditing({...editing,roles:e.target.checked?[...editing.roles,role]:editing.roles.filter((r:string)=>r!==role)})}/>{role}</label>)}</div><label className="checkbox"><input type="checkbox" checked={editing.active} onChange={e=>setEditing({...editing,active:e.target.checked})}/>Akun aktif</label>{error&&<div className="alert danger">{error}</div>}<div className="modal-actions"><button className="button primary" disabled={busy}>Simpan karyawan</button></div></form></Modal>}
  </section>;
}
