import {useState} from 'react';
import {api,action} from './api';
import {Modal} from './Modal';
import type {Employee,Outlet,PositionDefinition,ReplacementRule} from '../shared/domain';

type Props={tab:string;data:{outlets:Outlet[];positions:PositionDefinition[];employees:Employee[];policy:{replacementRules?:Record<string,ReplacementRule>}};onChange:()=>Promise<unknown>;onToast:(text:string)=>void};
export function ReplacementAdmin({tab,data,onChange,onToast}:Props){
  const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  const [editingOutlet,setEditingOutlet]=useState<Outlet|null>(null);const [outletName,setOutletName]=useState('');const [code,setCode]=useState('');const [name,setName]=useState('');const [quota,setQuota]=useState(2);
  const [rule,setRule]=useState<ReplacementRule|null>(null);const [deleting,setDeleting]=useState<{kind:'outlets'|'positions';id:string;name:string}|null>(null);
  async function save(path:string,body:unknown){setBusy(true);setError('');try{await action('/admin/'+path,body);await onChange();onToast('Perubahan berhasil disimpan.');setOutletName('');setCode('');setName('');setRule(null);setEditingOutlet(null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function remove(){if(!deleting)return;setBusy(true);setError('');try{await api('/admin/'+deleting.kind+'/'+encodeURIComponent(deleting.id),{method:'DELETE',key:crypto.randomUUID()});await onChange();setDeleting(null);onToast('Data berhasil dihapus.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  const label=(p:string)=>data.positions.find(item=>item[0]===p)?.[1]??p;
  return <div className="admin-content directory-manager">
    {error&&!rule&&!deleting&&!editingOutlet&&<div role="alert" className="alert danger">{error}</div>}
    {tab==='outlets'&&<><h2>Outlet cabang</h2><p className="muted">Atur outlet, lalu tempatkan karyawan melalui menu Karyawan.</p><form onSubmit={e=>{e.preventDefault();void save('outlets',{name:outletName});}} className="directory-add"><label className="field"><span>Nama outlet</span><input required minLength={2} maxLength={100} value={outletName} onChange={e=>setOutletName(e.target.value)}/></label><button disabled={busy} className="button primary">Tambah outlet</button></form><div className="table-scroll"><table><thead><tr><th>Outlet</th><th>Karyawan</th><th>Aksi</th></tr></thead><tbody>{data.outlets.map(o=><tr key={o.id}><td>{o.name}</td><td>{data.employees.filter(e=>e.outletId===o.id).length}</td><td><div className="employee-actions"><button className="button secondary" disabled={busy} onClick={()=>{setError('');setEditingOutlet({...o});}}>Edit outlet</button><button className="button secondary delete-link" disabled={busy} onClick={()=>{setError('');setDeleting({kind:'outlets',id:o.id,name:o.name});}}>Hapus outlet</button></div></td></tr>)}</tbody></table></div></>}
    {tab==='positions'&&<><h2>Master posisi</h2><p className="muted">Tambah posisi dan kuota awal. Posisi yang masih dipakai karyawan atau aturan PGS belum dapat dihapus.</p><form onSubmit={e=>{e.preventDefault();void save('positions',{code,name,quota});}}><div className="field-grid three"><label className="field"><span>Kode posisi</span><input required pattern="[A-Z][A-Z0-9_]{1,39}" title="Huruf kapital, angka, atau garis bawah, diawali huruf" value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/></label><label className="field"><span>Nama posisi</span><input required minLength={2} maxLength={60} value={name} onChange={e=>setName(e.target.value)}/></label><label className="field"><span>Kuota awal (orang/bulan)</span><input type="number" required min={0} max={1000} value={quota} onChange={e=>setQuota(Number(e.target.value))}/></label></div><button disabled={busy} className="button primary">Tambah posisi</button></form><div className="table-scroll"><table><thead><tr><th>Posisi</th><th>Kode</th><th>Kuota awal</th><th>Aksi</th></tr></thead><tbody>{data.positions.map(([p,l,q])=><tr key={p}><td>{l}</td><td>{p}</td><td>{q} orang</td><td><button className="button secondary delete-link" disabled={busy} onClick={()=>{setError('');setDeleting({kind:'positions',id:p,name:l});}}>Hapus posisi</button></td></tr>)}</tbody></table></div></>}
    {tab==='replacements'&&<><h2>Aturan pengganti sementara (PGS)</h2><p className="muted">Tentukan posisi dan outlet pengganti untuk setiap posisi cuti.</p><div className="table-scroll"><table><thead><tr><th>Posisi cuti</th><th>Posisi pengganti</th><th>Sumber outlet</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{data.positions.map(([p,l])=>{const current=data.policy.replacementRules?.[p];return <tr key={p}><td>{l}</td><td>{current?.sourcePositions.map(label).join(', ')||'Belum diatur'}</td><td>{current?[current.sameOutlet?'Outlet sama':'',current.otherOutlets==='ALL'?'Semua outlet lain':current.otherOutlets==='SELECTED'?current.outletIds.map(id=>data.outlets.find(o=>o.id===id)?.name??id).join(', '):''].filter(Boolean).join(' · ')||'—':'—'}</td><td>{current?.enabled?'Aktif':current?'Nonaktif':'Belum diatur'}</td><td><button className="button secondary" aria-label={'Atur PGS '+l} onClick={()=>{setError('');setRule(current??{position:p,enabled:true,sourcePositions:[],sameOutlet:true,otherOutlets:'NONE',outletIds:[]});}}>Atur</button></td></tr>;})}</tbody></table></div>
      {rule&&<Modal title={'PGS untuk '+label(rule.position)} onClose={()=>setRule(null)}><form className="pgs-rule-form" onSubmit={e=>{e.preventDefault();void save('replacement-rules',rule);}}>{error&&<div role="alert" className="alert danger">{error}</div>}<label className="checkbox"><input type="checkbox" checked={rule.enabled} onChange={e=>setRule({...rule,enabled:e.target.checked})}/>Aktifkan pemeriksaan pengganti</label><fieldset><legend>Posisi yang boleh menggantikan</legend><div className="directory-checks">{data.positions.map(([p,l])=><label className="checkbox" key={p}><input type="checkbox" checked={rule.sourcePositions.includes(p)} onChange={e=>setRule({...rule,sourcePositions:e.target.checked?[...rule.sourcePositions,p]:rule.sourcePositions.filter(item=>item!==p)})}/>{l}</label>)}</div></fieldset><label className="checkbox"><input type="checkbox" checked={rule.sameOutlet} onChange={e=>setRule({...rule,sameOutlet:e.target.checked})}/>Boleh dari outlet yang sama</label><label className="field"><span>Pengganti dari outlet lain</span><select value={rule.otherOutlets} onChange={e=>setRule({...rule,otherOutlets:e.target.value as ReplacementRule['otherOutlets']})}><option value="NONE">Tidak diperbolehkan</option><option value="ALL">Semua outlet lain dalam cabang</option><option value="SELECTED">Hanya outlet yang dipilih</option></select></label>{rule.otherOutlets==='SELECTED'&&<fieldset><legend>Outlet sumber yang diperbolehkan</legend><div className="directory-checks">{data.outlets.map(o=><label className="checkbox" key={o.id}><input type="checkbox" checked={rule.outletIds.includes(o.id)} onChange={e=>setRule({...rule,outletIds:e.target.checked?[...rule.outletIds,o.id]:rule.outletIds.filter(id=>id!==o.id)})}/>{o.name}</label>)}</div></fieldset>}<div className="inline-actions"><button type="button" disabled={busy} className="button secondary" onClick={()=>setRule(null)}>Batal</button><button disabled={busy} className="button primary">Simpan aturan PGS</button></div></form></Modal>}
    </>}
    {editingOutlet&&<Modal compact title="Edit outlet" onClose={()=>setEditingOutlet(null)}><form onSubmit={e=>{e.preventDefault();void save('outlets',editingOutlet);}}><label className="field"><span>Nama outlet</span><input required minLength={2} maxLength={100} value={editingOutlet.name} onChange={e=>setEditingOutlet({...editingOutlet,name:e.target.value})}/></label>{error&&<div role="alert" className="alert danger">{error}</div>}<div className="modal-actions"><button className="button primary" disabled={busy}>Simpan outlet</button></div></form></Modal>}
    {deleting&&<Modal compact title={'Hapus '+deleting.name+'?'} onClose={()=>setDeleting(null)}>{error&&<div role="alert" className="alert danger">{error}</div>}<p className="reason-text">Data yang masih digunakan tidak dapat dihapus. Riwayat cuti tetap tersimpan.</p><div className="inline-actions"><button className="button secondary" disabled={busy} onClick={()=>setDeleting(null)}>Batal</button><button className="button danger-button" disabled={busy} onClick={remove}>Konfirmasi hapus</button></div></Modal>}
  </div>;
}
